### ISSUE TITLE
POSIX shell compliance?

### ISSUE THREAD

**Issue by bharatvaj** [airblade/voom#23]
Hey, thanks for this script, I found this approach to be much better than the vim plugin method. And I have been using it for while and it works great! But I have a cross-platform setup working for me and it is very hard to get bash on windows working natively and even if it works, it is infamously known for it's slowness. A proper and stable way to make windows get any sort of UNIX snappiness is by using busybox-w32.

Are you interested in making voom POSIX shell compliant? It would also make voom to work on many other different systems where the constraints are necessary. I can take this up if you are busy.

**Comment by airblade** [comment]
That's great to hear!

I'm more than happy for voom to become POSIX shell compliant although I wouldn't be able to make time to do it myself.  My current process is "make shellcheck happy".  If you'd like to do it yourself, that would be great :)

**Comment by bharatvaj** [comment]
Hi, sorry it took me a while to create a PR for this. #24 . 

Before merging I want to clarify with you some of the left out POSIX changes and would take your advice.
[ ] 'local' may not be required for voom, since it is a really small script and it is undefined in POSIX. But it seems to be implemented in almost all the common shells, so I just left it there.
[ ] The ${//} parameter expansion is not POSIX compliant, but when used as substitute for basename, ${dir##*/}, shellcheck doesn't seem to mind. I'm yet to test this on an actual linux machine, so it's possible that it may fail on 'dash'. I've only tested this with 'ash' and it seems to work.

**Comment by airblade** [comment]
Thanks for this.

- `local`: I'm happy either way.
- `${dir##*/}`: I just tested on dash and it works.  Also the Pure sh Bible [say it's ok](https://github.com/dylanaraps/pure-sh-bible#prefix-and-suffix-deletion) which is good enough for me.

Out of interest, where is POSIX defined?

**Comment by bharatvaj** [comment]
I really should turn on phone notifications.

`${dir##*/}` is actually a strip command, I'm sorry for confusing it with replacement command `${//}` which is actually unavailable in dash.

The latest [commit](https://github.com/bharatvaj/voom/commit/ccd70fcfcf7526ad0e79cf8d394ff0649685706b) fixes it.

I left the local as it is.

I think this is the POSIX standard,
https://pubs.opengroup.org/onlinepubs/9699919799/

**Comment by airblade** [comment]
I didn't use `realpath` at the time because [it didn't exist](https://apple.stackexchange.com/a/450116/49772) on macOS until macOS 13 (Ventura).  I think it's ok to use now though.
