### ISSUE TITLE
realpath does not expand ~

### ISSUE THREAD

**Issue by airblade** [airblade/voom#25]
Support for plugin declarations like `~/path/to/local/repo` was added in 7d6dfe3.  Unfortunately 7bce740 broke it.

Specifically:

```diff
-ln -nfs "${line/#\~/$HOME}" "$PLUGINS_DIR/$plugin_name"
+ln -nfs "$(realpath $line)" "$PLUGINS_DIR/$plugin_name"
```

cc @bharatvaj

**Comment by airblade** [comment]
(Note to self: the `#` in the substring means front end of string.)

**Comment by airblade** [comment]
This seems to fix it:

```diff
diff --git i/voom w/voom
index 4d6fb78..57200b1 100755
--- i/voom
+++ w/voom
@@ -60,6 +60,7 @@ install_plugin() {
     if [ -n "$repo" ]; then
       git clone --depth 1 "$repo" "$PLUGINS_DIR/$plugin_name" >/dev/null 2>&1
     else
+      case "$line" in ~*) line="$HOME${line##\~}" ;; esac
       ln -nfs "$(realpath $line)" "$PLUGINS_DIR/$plugin_name"
     fi
     echo "installed $plugin_name"
```

@bharatvaj Please could you try this out on dash/ash/whatever?

**Comment by bharatvaj** [comment]
@airblade Really sorry about breaking this. I somehow missed this issue until now.

This is working under ash.
