### ISSUE TITLE
Unable to locate Plugins (part 2)

### ISSUE THREAD

**Issue by Integralist** [airblade/voom#5]
Hello again :-)

I'm just in the process of setting up a new laptop and I've hit the same problem with NeoVim that I had before (where the path isn't being picked up).

If I open `vim` then everything is fine and the plugins are located. If I open `nvim` on the other hand the plugins aren't located and I can tell immediately as one of the plugins is a custom colour scheme which isn't being applied.

- `mkdir -p ~/.vim/{autoload,bundle}`
- `curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim`
- `curl -LSso ~/.vim/plugins https://raw.githubusercontent.com/Integralist/dotfiles/master/voom/plugins`
- `curl -LSso /usr/local/bin/voom https://raw.githubusercontent.com/airblade/voom/master/voom`
- `chmod 744 /usr/local/bin/voom`
- `alias voom='VIM_DIR=~/.vim voom'`
- `curl -LSso ~/.vimrc https://raw.githubusercontent.com/Integralist/dotfiles/master/.vimrc`
- `curl -LSso ~/.nvimrc https://raw.githubusercontent.com/Integralist/dotfiles/master/.nvimrc`

If I run `:set runtimepath?` from Vim then I get:

```
runtimepath=~/.vim,~/.vim/bundle/Dockerfile.vim,~/.vim/bundle/Gist.vim,~/.vim/bundle/ack.vim,~/.vim/bundle/aws-vim,~/.vim/bundle/camelcasemotion,~/.vim/bundle/ctrlp.vim,~
/.vim/bundle/html5.vim,~/.vim/bundle/nofrils,~/.vim/bundle/rainbow_parentheses.vim,~/.vim/bundle/supertab,~/.vim/bundle/syntastic,~/.vim/bundle/tabular,~/.vim/bundle/unite.
vim,~/.vim/bundle/vim-clojure-highlight,~/.vim/bundle/vim-clojure-static,~/.vim/bundle/vim-commentary,~/.vim/bundle/vim-endwise,~/.vim/bundle/vim-fireplace,~/.vim/bundle/vi
m-github-colorscheme,~/.vim/bundle/vim-go,~/.vim/bundle/vim-leiningen,~/.vim/bundle/vim-markdown,~/.vim/bundle/vim-polyglot,~/.vim/bundle/vim-repeat,~/.vim/bundle/vim-sexp,
~/.vim/bundle/vim-sexp-mappings-for-regular-people,~/.vim/bundle/vim-surround,~/.vim/bundle/vim-textobj-rubyblock,~/.vim/bundle/vim-textobj-user,~/.vim/bundle/vim-tomorrow-
theme,~/.vim/bundle/vimfiler.vim,/usr/share/vim/vimfiles,/usr/share/vim/vim73,/usr/share/vim/vimfiles/after,~/.vim/bundle/vim-polyglot/after,~/.vim/bundle/vim-markdown/afte
r,~/.
```

But from NeoVim I get:

```
runtimepath=~/.config/nvim,/etc/xdg/nvim,~/.local/share/nvim/site,/usr/local/share/nvim/site,/usr/share/nvim/site,/usr/local/Cellar/neovim/HEAD/share/nvim/runtime,/usr/sh
are/nvim/site/after,/usr/local/share/nvim/site/after,~/.local/share/nvim/site/after,/etc/xdg/nvim/after,~/.config/nvim/after
```

I've tried using `ln -nfs ~/.vim ~/.nvim` to see if maybe it could pick up the plugins from there, but that didn't help.

I also tried `mkdir .config && ln -nfs ~/.vim ~/.config/.nvim` as it seemed from NeoVim that it was looking for `~/.config/nvim` by default.

I also tried modifying my `.nvimrc` to have an extra line at the top:

```
set runtimepath+=~/.nvim
source ~/.vimrc
```

But when starting up NeoVim and checking the runtimepath it still didn't have that path available.

Any ideas?

**Comment by Integralist** [comment]
Also, I removed NeoVim and re-installed it.

I then followed the explicit instructions it suggests:

```
The Neovim executable is called 'nvim'. 
To use your existing Vim configuration:
    ln -s ~/.vim ~/.config/nvim
    ln -s ~/.vimrc ~/.config/nvim/init.vim
```

But that also didn't help. Although the runtime shows it looks for `~/.config/nvim` it didn't actually make any difference in finding the plugins

**Comment by Integralist** [comment]
Oh and here is the result of running `:scriptnames` from within NeoVim:

```
  1: ~/.vim/init.vim
  2: /usr/local/Cellar/neovim/0.1.3/share/nvim/runtime/plugin/gzip.vim
  3: /usr/local/Cellar/neovim/0.1.3/share/nvim/runtime/plugin/man.vim
  4: /usr/local/Cellar/neovim/0.1.3/share/nvim/runtime/plugin/matchit.vim
  5: /usr/local/Cellar/neovim/0.1.3/share/nvim/runtime/plugin/matchparen.vim
  6: /usr/local/Cellar/neovim/0.1.3/share/nvim/runtime/plugin/netrwPlugin.vim
  7: /usr/local/Cellar/neovim/0.1.3/share/nvim/runtime/plugin/rplugin.vim
  8: /usr/local/Cellar/neovim/0.1.3/share/nvim/runtime/plugin/rrhelper.vim
  9: /usr/local/Cellar/neovim/0.1.3/share/nvim/runtime/plugin/shada.vim
 10: /usr/local/Cellar/neovim/0.1.3/share/nvim/runtime/plugin/spellfile.vim
 11: /usr/local/Cellar/neovim/0.1.3/share/nvim/runtime/plugin/tarPlugin.vim
 12: /usr/local/Cellar/neovim/0.1.3/share/nvim/runtime/plugin/tohtml.vim
 13: /usr/local/Cellar/neovim/0.1.3/share/nvim/runtime/plugin/tutor.vim
 14: /usr/local/Cellar/neovim/0.1.3/share/nvim/runtime/plugin/vimballPlugin.vim
 15: /usr/local/Cellar/neovim/0.1.3/share/nvim/runtime/plugin/zipPlugin.vim
```

If this helps at all?

**Comment by airblade** [comment]
Hello again :)  Glad you got it working :beer:
