### ISSUE TITLE
Cannot pull with rebase error

### ISSUE THREAD

**Issue by Integralist** [airblade/voom#9]
I've just noticed the following error...

```
$ voom update
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.
```

Any ideas on where I can start to debug this? Thanks :-)

**Comment by airblade** [comment]
Hmm, there is absolutely no error handling anywhere in the script ;)

I should think [this line](https://github.com/airblade/voom/blob/59f7de5fc97445e3c8f6008a62849a7146392c7f/voom#L76) is tripping up.  You could move it below the `echo` in the following (code) line to find out which plugin has the unstaged changes.

I suppose the correct thing to do is catch any errors when git-pulling, display them nicely to the user, and press on.

**Comment by Integralist** [comment]
OK so I figured out it was one of my own plugins that was in a inconsistent state :-)


Annoyingly I fixed the issue and then realised I should've left it broken so I could use...

```bash
error() {
  local parent_lineno="$1"
  local message="$2"
  local code="${3:-1}"
  if [[ -n "$message" ]] ; then
    echo "Error on or near line ${parent_lineno}: ${message}; exiting with status ${code}"
  else
    echo "Error on or near line ${parent_lineno}; exiting with status ${code}"
  fi
  exit "${code}"
}

trap 'error ${LINENO}' EXIT
```

...to try and capture any errors (as I would've opened a PR for you), but now nothing's broken so decided to leave it.
